### ISSUE TITLE
DISQUS 제목 변경

### ISSUE THREAD

**Issue by marocchino** [ruby-korea/ruby-korea.github.io#34]
https://disqus.com/home/forum/ruby-korea/ 의 제목이 아직 `루비(Ruby) 한글 문서` 입니다.
#29 와 마찬가지로 한국어로 바꾸어 주셨으면 합니다.

**Comment by nacyot** [comment]
넵. 확인하겠습니다.

**Comment by nacyot** [comment]
변경했습니다.

**Comment by marocchino** [comment]
:+1:
