### ISSUE TITLE
만료된 링크 정리 

### ISSUE THREAD

**Issue by AkiaCode** [ruby-korea/ruby-korea.github.io#39]
저가 링크를 하나 씩 눌려보는 데 이미 없어진 블로그나 링크들이 있으므로 따로 정리를 해서 한꺼번에 없애야 할 거 같습니다.

**Comment by AkiaCode** [comment]
## 글
레일즈 5의 액션 케이블을 활용한 채팅 앱 구현
주피터(Jupyter) - IRuby Notebook 보충
루비 스타일(3) – 말하는 듯한 코딩
루비 스타일(2) – 들여쓰기(indent)로부터의 탈출
워드프레스에서 지킬로 본진 이동
도커(Docker)로 루비 온 레일스 어플리케이션 배포하기 (1) 어플리케이션 이미지 만들기
루비의 꽃, 열거자 Enumerable 모듈
쿡패드(Cookpad) 루비 스타일 가이드
AngularJS + Rails 프로젝트 구성
Padrino Blog Tutorial
Rspec과 Guard를 활용한 루비 테스트 자동화
Thinking about Ruby’s Class Declaration Syntax, Object Creation Mechanism
루비의 Each와 Map의 차이
9분만에 배우는 루비(Ruby)
JavaScript를 Ruby처럼 작성하기
Ruby의 철학에 관한 마츠모토 유키히로의 인터뷰 Part 1
루비 온 레일스 아키텍처 디자인
Ruby 와 Rails 배우고 싶을때
Ruby, Rails 스터디 이전 발표 자료
- TDD는 죽었다 - Rails를 만든 DHH의 글
루비 테스트 프레임워크 RSpec 2.14 매쳐(Matchers)

## 동영상
도커(Docker)로 루비 온 레일스(Ruby on Rails) 어플리케이션 배포하기 1/2
Zero to Pinterest UI(Dev.Study.Archive)
RORLab Podcasts

### 문서, 사이트
이상한 모임 : 루비
레일스 가이드 RubyKr
HappyRails
Better Specs

**Comment by marocchino** [comment]
베터 스팩은 포멧을 yaml로 바꾸면서 검수안되는 번역을 버렸나보네요. 오래걸리는건 아니니 작업해서 pr보내겠습니다.
나머지는 지울께요. 알려주셔서 감사합니다.

**Comment by marocchino** [comment]
강사룡님 링크는 워드프레스가 살아있어서 복원해두었습니다.

**Comment by AkiaCode** [comment]
> 베터 스팩은 포멧을 yaml로 바꾸면서 검수안되는 번역을 버렸나보네요. 오래걸리는건 아니니 작업해서 pr보내겠습니다.
> 나머지는 지울께요. 알려주셔서 감사합니다.

넵
